In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv("rawdata.csv")

In [10]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
count,7.869400e+04,78692.000000,77691.000000,6.921800e+04,69376.000000,77691.000000,78267.000000,78265.000000,77269.000000,68804.000000,...,72894.000000,49713.000000,73489.000000,74470.000000,57680.000000,56828.000000,36917.000000,67171.000000,76222.000000,73430.000000
mean,7.429238e+05,5430.286471,5417.396717,2.128240e+04,134.662001,118.743826,8965.988111,71.393497,71.212973,204.718066,...,19133.403480,13.312799,257.534871,7.809301,10.527642,32.652882,50.952758,3.031553,73.154220,0.727432
std,5.169702e+06,33480.103666,32963.628052,1.253299e+05,734.731397,670.245949,17412.235307,173.981249,147.043462,361.088519,...,19780.851788,19.929338,118.677633,3.958182,10.402790,13.473538,31.765209,2.465078,7.551635,0.150069
min,1.000000e+00,-74347.000000,-6223.000000,1.000000e+00,-1918.000000,-232.143000,0.001000,-2153.437000,-276.825000,0.001000,...,661.240000,0.100000,79.370000,0.990000,0.100000,7.700000,1.188000,0.100000,53.280000,0.394000
25%,8.430000e+02,2.000000,6.429000,4.200000e+01,0.000000,0.000000,178.762500,0.168000,1.086000,6.238000,...,4466.507000,0.500000,167.295000,5.290000,1.900000,21.600000,20.859000,1.300000,67.880000,0.602000
50%,9.164500e+03,66.000000,79.286000,2.850000e+02,2.000000,1.143000,1230.692000,7.077000,9.328000,35.569000,...,12951.839000,2.000000,242.648000,7.110000,6.300000,31.400000,49.839000,2.400000,74.530000,0.748000
75%,9.943175e+04,719.000000,750.214500,2.778750e+03,17.000000,13.000000,8631.262000,62.824000,70.411000,218.986750,...,27216.445000,21.200000,329.635000,10.080000,19.300000,41.100000,83.241000,3.861000,78.730000,0.848000
max,1.339433e+08,880812.000000,739642.714000,2.901909e+06,17904.000000,14432.857000,160603.119000,8652.658000,2648.773000,2564.763000,...,116935.600000,77.600000,724.417000,30.530000,44.000000,78.100000,98.999000,13.800000,86.750000,0.957000